version: 2
jobs:

  build:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm run build-frontend

      - save_cache:
          paths:
            - client/node_modules
          key: v1-client-dependencies-{{ checksum "client/package.json" }}

      - run: npm run build-server

      - save_cache:
          paths:
            - server/node_modules
          key: v1-server-dependencies-{{ checksum "server/package.json" }}

      - save_cache:
          paths:
            - ~/repo
          key: built-project-{{ .BuildNum }}

  deploy:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
          - built-project-{{ .BuildNum }}
          - built-project-
      - run:
          name: Run heroku setup script
          command: bash .circleci/setup-heroku-client.sh
      - run:
          name: Deploy Master to Heroku
          command: git push --force https://git.heroku.com/jira-game.git HEAD:master
      - run:
          name: Restart Heroku
          command: heroku restart --app jira-game

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
              